language: python
python:
  - 3.7
dist: xenial
sudo: true
cache: pip
branches:
  only:
    - master
install:
  - pip install -U pip
  - pip install codecov poetry
  - poetry install
script:
  - coverage run -m doctest chain/utils/elliptic.py
  - coverage run -m unittest discover .
after_success:
  - codecov
