[tool.poetry]
name = "minichain"
version = "0.1.0"
description = "Mini blockchain in Python"
authors = [
    "Weiliang Li <to.be.impressive@gmail.com>"
]

[tool.poetry.dependencies]
python = "^3.8"
coincurve = "^13.0.0"
kademlia = "^2.2"
eth_keys = "^0.3.3"
pysha3 = "^1.0.2"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
mypy = "^0.790"
flake8 = "^3.8.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
